// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Todolistapplication.Models;

#nullable disable

namespace Todolistapplication.Migrations
{
    [DbContext(typeof(TodolistDbContext))]
    [Migration("20221116123455_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Todolistapplication.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("item_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("item_Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("item_created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("item_updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("user_infoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("user_infoId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Todolistapplication.Models.user_info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("user_infos");
                });

            modelBuilder.Entity("Todolistapplication.Models.TodoItem", b =>
                {
                    b.HasOne("Todolistapplication.Models.user_info", "user_info")
                        .WithMany("TodoItems")
                        .HasForeignKey("user_infoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_info");
                });

            modelBuilder.Entity("Todolistapplication.Models.user_info", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
